### ISSUE TITLE
Nested selectors in Scss are not indented in the Vista preview

### ISSUE THREAD

**Issue by tylerfowle** [liuchengxu/vista.vim#165]
Nested selectors in Scss are not indented in the Vista preview

![Screen Shot 2019-10-18 at 11 05 11 AM](https://user-images.githubusercontent.com/7574003/67110048-77932b00-f197-11e9-8756-8aff0201f01d.png)

this quickly gets confusing, and hard to navigate

![Screen Shot 2019-10-18 at 11 10 01 AM](https://user-images.githubusercontent.com/7574003/67110248-e6708400-f197-11e9-9e1f-b38ab24448b5.png)

**Comment by liuchengxu** [comment]
Only the ctags executive supports the nested view, the LSP executives don't. See the README notes.

**Comment by liuchengxu** [comment]
Hmm, seeming you also tried the ctags executive, thus I reopen it. But you did not provide a detailed report and I do not write scss, so I can't help more.

**Comment by tylerfowle** [comment]
@liuchengxu correct, it is the same with the LSP executives.  I'm not sure what information you need.
![Screen Shot 2019-10-18 at 1 25 11 PM](https://user-images.githubusercontent.com/7574003/67118637-eaf26800-f1aa-11e9-9a8d-62b346a54506.png)

**Comment by liuchengxu** [comment]
I don't write scss, so if you provide a sample scss file, I may take a look later.

**Comment by tylerfowle** [comment]
```scss
@import "compass";
@import "blueprint";
@import "blueprint/fancy_type";

$blueprint-grid-columns:     5;
$blueprint-grid-width:       150px;
$blueprint-grid-margin:      20px;

$blueprint-font-family:      Helvetica Neue, Arial, Helvetica, sans-serif;
$blueprint-fixed-font-family:'andale mono', 'lucida console', monospace;
$blueprint-font-size:        12px;

$text-color:                 #555555;
$light-text-color:           #a0a0a0;
$quote-text-color:           #f27a00;
$disclosure-text-color:      #ed7c06;

$thick-border:               8px solid black;
$dotted-border:              1px dotted #999999;

$header-background-color:    #f07c05;
$paging-background-color:    black;
$unfocused-background-color: #f1f0ec;
$quote-background-color:     #f1f0ec;

$story-title-color:          #f07c05;

// functions
@function color($color) {
    @return map-get($colors, $color);
}


// mixins
@mixin clearfix {
    &:after {
        clear: both;
    }

    &:before,
    &:after {
        display: table;
        content: ' ';
    }
}

@mixin border-box {
    box-sizing: border-box;
}


// includes
@include global-reset;
@include blueprint-typography;

// html elements
body {
    background: $unfocused-background-color image_url("white-bg.jpg") repeat-y 50% 0;
    color: $text-color;
}

header {
    background: red;
}

aside {
    color: blue;
}

footer {
    font-family: monospace;
}


// . is a class
.content_wrapper {
    @include container;
    width: 910px;
}

// # is an id
#header {
    height: 72px;
    background: $header-background-color;
    @include clearfix;

    h1 {
        color: white;
        @include float-left;
        a {
            @include replace-text("logo.jpg");
            width: 116px;
            height: 72px;
            display: block;
            text-decoration: none;
            &:hover {
                color: red;
            }
        }
    }

    ul {
        @include horizontal-list;
        padding: 0 0 0 25px;
        li {
            @include incr(18px);
            padding: 0 20px 0 0;
            text-transform: uppercase;
            a {
                @include border-box;
                color: #febf0f;
                text-decoration: none;
                width: 100px;
                height: 72px;
                display: block;
            }
            &#header-threads a {
                @include replace-text("header-threads-text.jpg");
            }
            &#header-timeline a {
                @include replace-text("header-timeline-text.jpg");
            }
        }
    }
}

#paging {
    background: $paging-background-color;
    height: 33px;
    padding: 15px 0 0 0;

    h6 {
        @include float-left;
        color: #908f8b;
        padding-right: 20px;
        text-transform: uppercase;
        a {
            color: #f07b07;
            text-decoration: none;
        }
    }

    ul {
        @include horizontal-list;
        li {
            padding: 3px 4px;
            a {
                color: #4c4c4c;
                @include replace-text("thread-paging-inactive-bullet.jpg");
                width: 10px;
                height: 10px;
                display: block;
            }
            &.active a {
                color: #f17d06;
            }
        }
    }
}

#content {
    position: relative;
    #previous {
        position: absolute;
        top: 0;
        left: 0;
        text-align: right;
    }
    #next {
        position: absolute;
        top: 0;
        right: 0;
        text-align: left;
    }
}

#thread {
    @include container;
    width: 910px;
    top: 0px;
    left: 0px;

    @include transition-property(left);
    @include transition-duration(0.5s);
    @include transition-timing-function(ease-in-out);

    @for $i from 0 through 30 {
        &.position#{$i} {
            left: ($i * -910px);
        }
    }
}

.js {
    #content {
        overflow: hidden;
        width: 100%;
    }

    #thread {
        padding: 0;
        width: 5000px;
        position: absolute;
    }
}

.story {
    @include float-left;
    width: 810px;
    padding: 0 50px;

    h4.date {
        @include float-right;
        @include span(1);
        background: $unfocused-background-color;
        padding: 10px 20px;
        @include border-radius(3px);
    }

    h1 {
        padding: 40px 0 20px 0;
        border-bottom: $thick-border;
        color: $story-title-color;
        @include incr(30px);
    }

    .artifacts {
        @include column(3);

        .row {
            @include clearfix;
            border-bottom: $dotted-border;
            margin-bottom: $blueprint-grid-margin;
        }

        .artifact {
            color: $light-text-color;
            img {
                margin-bottom: 0.5em;
            }
            a {
                font-weight: bold;
                text-decoration: none;
                color: #0a83e0;
            }
        }

        .threecol { @include column(3); }
        .twocol   { @include column(2); }
        .onecol   { @include column(1); }
        .last     { @include last;      }
    }

    .information {
        @include column(1.6, true);
        border-bottom: $dotted-border;
        margin-left: 40px;

        h2 {
            @include incr(20px, $blueprint-font-size, 35px);
        }

        .textblock p {
            @include incr(13px, $blueprint-font-size, 26px);
        }

        .quote {
            color: $quote-text-color;
            blockquote {
                @include incr(18px, $blueprint-font-size, 30px);
                color: $quote-text-color;
                margin: 0;
                padding: 12px 18px;
                background: $quote-background-color;
                @include border-radius(5px);
            }
            cite {
                display: block;
                padding: 0.5em 18px 1.5em 18px;
            }
        }

        .disclosure {
            border-top: $dotted-border;
            h5 {
                padding: 10px 0;
                margin: 0;
                color: $disclosure-text-color;
            }
            p {
                color: #a8a8a8;
            }
        }
    }
}

#footer {
    @include container;
    background: white;
    width: 810px;
    padding: $blueprint-grid-margin 0;

    .inner {
        border-top: $thick-border;
        padding: 30px 0;
    }

    p {
        @include float-right;
        @include incr(10px);
        color: #b3b3b3;
    }

    ul {
        @include horizontal-list;

        li {
            padding: 0 30px 0 0;
            a {
                text-decoration: none;
                color: #ef7a06;
            }
        }
    }
}
```
